import{a as q,i as l,S}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",P="46950452-7815ceb93240c1d1876de68f7";async function R(r,t=1,s=15){try{const{data:i}=await q.get(v,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}});return console.log(i),i.hits.length===0?{hits:[]}:i}catch(i){return console.log(i),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"}),{hits:[]}}}const u=document.querySelector(".list");function E(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:a,comments:x,downloads:w})=>`
        <div class="gallery-item">
            <a href="${i}">
                <img src="${s}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="text2">Likes:</b> ${o}</p>
                <p class="info-text"><b class="text2">Views:</b> ${a}</p>
                <p class="info-text"><b class="text2">Comments:</b> ${x}</p>
                <p class="info-text"><b class="text2">Downloads:</b> ${w}</p>
            </div>
        </div>
    `).join("");u.insertAdjacentHTML("beforeend",t)}const h=document.querySelector(".search-form"),M=document.querySelector(".search-form input"),m=document.querySelector(".loader"),n=document.querySelector(".load-more");let d,c=1,f=0,y=0,p="";n.style.display="none";h.addEventListener("submit",O);n.addEventListener("click",$);async function O(r){r.preventDefault();const t=M.value.trim();if(u.innerHTML="",t==="")return l.info({title:"Error",message:"Please enter a search query.",position:"topRight",backgroundColor:"red"});n.style.display="none",p=t,c=1,f=0,y=0,u.innerHTML="",b(),await g(p,c),L(),h.reset()}async function g(r,t){try{const s=await R(r,t);if(s.hits.length===0){n.style.display="none",l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"});return}f=s.totalHits,y+=s.hits.length,E(s.hits),H(),t>1&&C(),D()}catch{l.error({position:"topRight",message:"Oooopppps"})}}async function $(){c++,n.disabled=!0,b(),await g(p,c),L()}function b(){m.style.display="block"}function L(){m.style.display="none"}function D(){y>=f?(n.style.display="none",l.error({message:"Finish",position:"topRight"})):(n.style.display="block",n.disabled=!1)}function H(){d?d.refresh():d=new S(".gallery-item a",{captionsData:"alt",captionDelay:250})}function C(){const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
